### ISSUE TITLE
Dextop can't connect to VNC

### ISSUE THREAD

**Issue by kaannabdullah** [nathaneltitane/dextop#12]
After installed dextop on termux i am just trying to start container-session it opens VNC and VNC says it cant be connected.  
![WhatsApp Image 2023-02-15 at 3 50 39 PM](https://user-images.githubusercontent.com/106771030/219032314-a7944828-3710-4e8d-95c1-84f2b56e61a5.jpeg)
![WhatsApp Image 2023-02-15 at 3 50 38 PM](https://user-images.githubusercontent.com/106771030/219032337-dfe0b26e-f59b-45ed-ae82-a7c737a2f63d.jpeg)

**Comment by nathaneltitane** [comment]
> After installed dextop on termux i am just trying to start container-session it opens VNC and VNC says it cant be connected. ![WhatsApp Image 2023-02-15 at 3 50 39 PM](https://user-images.githubusercontent.com/106771030/219032314-a7944828-3710-4e8d-95c1-84f2b56e61a5.jpeg) ![WhatsApp Image 2023-02-15 at 3 50 38 PM](https://user-images.githubusercontent.com/106771030/219032337-dfe0b26e-f59b-45ed-ae82-a7c737a2f63d.jpeg)

I can confirm that version 01-28-2023 is working as expected. I have just tested with remotix and bvnc on both my devices.

Please make sure to run container-session -x to kill the display service and completely logout and terminate both termux and your vnc viewer application and then re-run in this order after opening termux:

first for the termux instance:

`container-session -o`

and then for the actual linux distribution container you have chosen, after killing termux and the viewer once again:

`container-session -u termux`
`container-session -o`

Please report back with what happens for each.

At worst, please make sure to purge and reinstall Dextop completely after making sure termux is fully up to date and that your wireless or wired connection is stable.

**Comment by kaannabdullah** [comment]
I was jsut using container-session -o and didn't knew about container-session -u termux. After trying in this queue it worked. Thanks for help and i think it will be good addition to the instructions. <3
