### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by GameDevPro32** [nathaneltitane/dextop#13]
I tried installing it but after a while of downloading it gives an error saying this : " /data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /usr/share/icons: No such file or directory "

**Comment by nathaneltitane** [comment]
Please post a screenshot of where the error happens to identify the step the install is at.

**Comment by GameDevPro32** [comment]
Here is the screenshot

**Comment by nathaneltitane** [comment]
> 

No screenshot received - please upload to gihub directly

**Comment by GameDevPro32** [comment]
![Screenshot_20230325-215312.png](https://user-images.githubusercontent.com/98618028/227741380-8c8a7f5c-aaeb-4a6d-98e5-89e076516c57.png)

**Comment by nathaneltitane** [comment]
Are you installing from scratch or over another install?

**Comment by GameDevPro32** [comment]
From scratch,why ?

**Comment by nathaneltitane** [comment]
> From scratch,why ?

Is it a new install? Yes? No?

**Comment by GameDevPro32** [comment]
Yes

**Comment by nathaneltitane** [comment]
i suggest clearing all caches and data for termux after backup and restarting the installation process making sure you have proper wifi connectivity.

**Comment by GameDevPro32** [comment]
I did that three times

**Comment by nathaneltitane** [comment]
Going to run a clean install on my device again to validate.

**Comment by nathaneltitane** [comment]
> I did that three times

I just ran the setup, from scratch, after backing up termux and purging all cache and storage on android for the application.

My setup completed successfully without errors and sent me to the Dextop login prompt.

Please make sure to grant the storage permission in a timely manner when prompted.

I also suggest you verify your Android device settings for anything that either makes your wifi or data disconnect on sleep as it seems your install was subject to intermittent connection to the internet.

![image](https://user-images.githubusercontent.com/5674757/227743207-62b4ca56-cf3e-49ee-bb05-05cb06e5542d.png)

**Comment by GameDevPro32** [comment]
My internet works fine. I ran the bash dextop command even after It showed me an error. Plus I deleted and reinstalled termux tre times to try and install it. Is there any way I can create the missing directory so download can proceed ?

**Comment by nathaneltitane** [comment]
> My internet works fine. I ran the bash dextop command even after It showed me an error. Plus I deleted and reinstalled termux tre times to try and install it. Is there any way I can create the missing directory so download can proceed ?

No since it is created based on the default selection for the up to date ubuntu distribution container.
Once again, be sure to actually remove all data and storage traces of your previous termux install and keep your device awake.

I just ran the install on both my devices and both pulled through properly using the unattended default installation.

I suggest looking in the install logs under ~/.local/var/log as suggested in the readme to see what happens with the container setup.

**Comment by GameDevPro32** [comment]
Maybe it's because my phone is 32 bit amvl8 ?

**Comment by nathaneltitane** [comment]
> 

Possibly so, as it may be a factor, I only run arm64 devices: did you get a 'valid architecture' check at any point in your setup?

**Comment by GameDevPro32** [comment]
No I don't think I did

**Comment by nathaneltitane** [comment]
> Maybe it's because my phone is 32 bit amvl8 ?

Supported architectures are:

![image](https://user-images.githubusercontent.com/5674757/227743955-13462b13-01d0-421a-8b0b-54cd578301e0.png)

**Comment by GameDevPro32** [comment]
Well that explains everything sorry for wasting your time bro I will just try this on my other phone . Bye

**Comment by nathaneltitane** [comment]
> Well that explains everything sorry for wasting your time bro I will just try this on my other phone . Bye

No worries! I will implement an architecture 'pre-flight' check - already added requirement to readme update!

Thank you for reporting this!
