### ISSUE TITLE
Install fails with -c option

### ISSUE THREAD

**Issue by anonimo82** [nathaneltitane/dextop#14]
Hello everybody.
I'm using a SM-G965F, everything went fine with a "classic" install (`curl -s -L run.dxtp.app > dextop && bash dextop`)
But, after deleting Termux' data and retrying installation with -c (`curl -s -L run.dxtp.app > dextop && bash dextop -c`), installation fails with errors:

```
[ / ] Copying ////////////////////////////////////////////////////////// [ Arc ]

cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc': No such file or directory
[ / ] Copying ///////////////////////////////////////////////////// [ Arc-Dark ]

cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Dark': No such file or directory
[ / ] Copying /////////////////////////////////////////////////// [ Arc-Darker ]

cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Darker': No such file or directory
[ / ] Copying ////////////////////////////////////////////////// [ Arc-Lighter ]

cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Lighter': No such file or directory
/data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes: No such file or directory
```

What should I do?

Thanks for any help

**Comment by nathaneltitane** [comment]
> Hello everybody.
> I'm using a SM-G965F, everything went fine with a "classic" install (`curl -s -L run.dxtp.app > dextop && bash dextop`)
> But, after deleting Termux' data and retrying installation with -c (`curl -s -L run.dxtp.app > dextop && bash dextop -c`), installation fails with errors:
> 
> ```[ / ] Copying ////////////////////////////////////////////////////////// [ Arc ]
> 
> cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc': No such file or directory
> [ / ] Copying ///////////////////////////////////////////////////// [ Arc-Dark ]
> 
> cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Dark': No such file or directory
> [ / ] Copying /////////////////////////////////////////////////// [ Arc-Darker ]
> 
> cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Darker': No such file or directory
> [ / ] Copying ////////////////////////////////////////////////// [ Arc-Lighter ]
> 
> cp: cannot stat '/data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes/Arc-Lighter': No such file or directory
> /data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes: No such file or directory```
> 
> What should I do?
> 
> Thanks for any help, regards =)

probably a mishandling from my part for that option for those extra gimmicks. the '-c' parameter refers to 'console' setup, I.e.: no desktop environment nor any directories relative to DEs in general hence the errors.

Your container still exists and is accessible, but will not load any graphical components as there is no desktop environment to back that request.

This option is intended as a "terminal only" instance for customizing etc.

Ill clean the dextop setup requirements to skip the themes and icons on console setup.

thanks

**Comment by anonimo82** [comment]
Yes, it's indeed what I was looking for: console only, with framebuffer.

@nathaneltitane

**Comment by nathaneltitane** [comment]
> Yes, it's indeed what I was looking for: console only, with framebuffer.
> 
> @nathaneltitane

Pretty sure it's working. Stop termux and exit, and relaunch it using the usual commands for container or just termux and you're set.

**Comment by anonimo82** [comment]
Here's the result running the container after a failed installation: 
![Screenshot_20230408-175329_Termux](https://user-images.githubusercontent.com/38261009/230730810-e0cbdac3-c6ee-4439-a27f-c3cabf431479.jpg)
![Screenshot_20230408-175318_bVNC Free](https://user-images.githubusercontent.com/38261009/230730814-01de8d03-0c55-43b4-a6bf-0be88c676292.jpg)


And here is trying to resume install:
![Screenshot_20230408-175525_Termux](https://user-images.githubusercontent.com/38261009/230730861-f892cbd1-62bf-4f3b-8214-e0aa1220e96f.jpg)

**Comment by nathaneltitane** [comment]
you should launch using `container-session -u termux` - container-session -o is for graphical user interface only, i.e.: non-console setups...

**Comment by anonimo82** [comment]
Yay!!!!!!!!!!
It now WORX!!!!!!!
