### ISSUE TITLE
framebuffer?

### ISSUE THREAD

**Issue by anonimo82** [nathaneltitane/dextop#15]
Hello again.
How can I use framebuffer powered applications, such as fbi image viewer?
Edit: I tried installing xserver-xorg-video-fbdev

Thanks for any help.

**Comment by anonimo82** [comment]
@nathaneltitane anyone?

**Comment by nathaneltitane** [comment]
> Hello again. How can I use framebuffer powered applications, such as fbi image viewer? Edit: I tried installing xserver-xorg-video-fbdev
> 
> Thanks for any help.

I don't see why it would not work, but that ought to be done using a distribution container - I cannot speak for termux-only application repacks or their behavior.

**Comment by anonimo82** [comment]
That's a Debian package, fbi, a Framebuffer image viewer.
This is the output of trying to open it:
![Screenshot_20230411-040928_Termux](https://user-images.githubusercontent.com/38261009/231037475-a5f1d27d-b0e7-4e55-a7d5-df6cd82b0a9a.jpg)

I'm inside a Dextop container

Here there are info about fbi:

```

[ termux ] >_ $ container-session -u termux
[ ¤ ] Setting up session /////////////////////////// [ container // 03-25-2023 ]

[ > ] Authenticating...

[ ✓ ] Valid user name ///////////////////////////////////////////// [ 'termux' ]

[ termux ] >_ $ apt show fbi
Package: fbi
Version: 2.10-4ubuntu1
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Moritz Muehlenhoff <jmm@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 151 kB
Depends: libc6 (>= 2.17), libexif12 (>= 0.6.21-1~), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgif7 (>= 5.1), libjpeg8 (>= 8c), libpng16-16 (>= 1.6.2-1), libtiff5 (>= 4.0.3)
Recommends: ghostscript
Suggests: imagemagick
Homepage: https://www.kraxel.org/blog/linux/fbida/
Download-Size: 53.1 kB
APT-Manual-Installed: yes
APT-Sources: http://ports.ubuntu.com/ubuntu-ports kinetic/universe arm64 Packages
Description: Linux frame buffer image viewer
 This is an image viewer for Linux frame buffer devices.  It has
 built-in support for a number of common image file formats.  For
 unknown files, it tries to use convert from the ImageMagick package
 as an external converter.
 It also includes fbgs, a Postscript and PDF viewer.

[ termux ] >_ $
```

**Comment by nathaneltitane** [comment]
Try running the command with 'sudo' - fbi requires ioctl control access through /dev/fb0

You may want to explicitate the device to run fbi through as well

See here: [fbi over ssh](https://unix.stackexchange.com/questions/416785/how-to-send-commands-to-fbi-over-ssh)

**Comment by anonimo82** [comment]
Uhm, I don't have device /dev/fb0
and running commands suggested in your link didn't work, unfortunately.
I can't right now, but I'll upload the exact error I get ASAP.

Thanks for your time and your help by the way.

**Comment by anonimo82** [comment]
![Screenshot_20230411-205847_Termux](https://user-images.githubusercontent.com/38261009/231263596-9fe1c6ea-9088-4208-8999-c58d7da6399a.jpg)
![Screenshot_20230411-210023_Termux](https://user-images.githubusercontent.com/38261009/231263620-1bbf78c3-8e2f-4257-9fa7-89d1f67ddf09.jpg)
![Screenshot_20230411-210126_Termux](https://user-images.githubusercontent.com/38261009/231263634-d602ed30-7649-4980-b845-a6bee32be0c9.jpg)

**Comment by anonimo82** [comment]
Note I issued both suggested commands, both with and without sudo.
I also did `ls /dev/fb0` with no luck, and tried the method suggested in the first StackExchange post.

Still no luck )=

**Comment by anonimo82** [comment]
I'd like to try something different.
How can I connect my Termux instance with Telnet/SSH/or so?

**Comment by nathaneltitane** [comment]
> I'd like to try something different. How can I connect my Termux instance with Telnet/SSH/or so?

Your question pertains to basic network connectivity usage. Please do a quick google search on the topic as it is not directly relevant to the Dextop project. I'm sure this has been asked many times over.

**Comment by anonimo82** [comment]
Yes, sorry. =)
