### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by mailes764** [nathaneltitane/dextop#16]
Hello, tried installing this and when I paste the prompt to install nothing happens :(
S22, android 13, termux v118, API v51
![Screenshot_20230411_110950_Termux](https://user-images.githubusercontent.com/130444549/231097593-11f1e0a0-c384-4d6b-8d60-9ccf61a059da.png)

**Comment by nathaneltitane** [comment]
Most probably some kind of data/wifi interruption. All services and domain names are up and running.
Please purge all Termux data, restart your device, make sure you are connected to some kind of internet connection (WiFi/LTE) and ensure that your device'S sleep settings do not disable that connection.
