### ISSUE TITLE
Getting back screen with mouse in vnc

### ISSUE THREAD

**Issue by NoBloodyABCorD** [nathaneltitane/dextop#17]
I've completely wiped the temux data and installed fresh.  Ran the dextop script with no error.  I appear to be connecting correctly, however the vnc client gives me a black screen with mouse cursor.
![Screenshot_20230413_171001_Termux](https://user-images.githubusercontent.com/23297624/231883989-83bd1174-5c2f-40ad-9c3c-66f01ae292a5.jpg)

![Screenshot_20230413_170912_Remotix](https://user-images.githubusercontent.com/23297624/231884236-41e713d8-c46f-43e0-84f2-1834a20fcc9b.jpg)

**Comment by nathaneltitane** [comment]
Please fully yerminate your vnc application through the android app and process manager and in termux type ```container-session -x``` then terminate termux and force reload a new vnc selection for your device using ```container-session -n```
after logging in of course.

p.s. all utilities have their --help parameter output
