### ISSUE TITLE
(Feature Enhancement Request) Alternative X Servers?

### ISSUE THREAD

**Issue by ShadowEO** [nathaneltitane/dextop#18]
Could it be possible to implement the native Android X Servers such as Pelya's XSDL (https://github.com/pelya/xserver-xsdl) or even Termux:X11?

This would provide a configurable X Server (such as resolution and DPI) and reduce the overhead overall by cutting out the VNC server and Xvfb as a middleman. Pelya's XSDL also includes PulseAudio support allowing sound support from the Linux chroot and doesn't require root to run even.

**Comment by nathaneltitane** [comment]
> Could it be possible to implement the native Android X Servers such as Pelya's XSDL (https://github.com/pelya/xserver-xsdl) or even Termux:X11?
> 
> This would provide a configurable X Server (such as resolution and DPI) and reduce the overhead overall by cutting out the VNC server and Xvfb as a middleman. Pelya's XSDL also includes PulseAudio support allowing sound support from the Linux chroot and doesn't require root to run even.

Thanks for your suggestion: Termux:X11 is in the pipeline, although, given how unstable it is, I may have to wait on implementing it for now.

Pelya's XSDL implementation also has its drawbacks and was not added as a feature from the get-go given the enormous amounts of workarounds needed to get it working reliably.

I will look at  Termux:X11's status and remap the implementation for soon enough though as it make more sense to keep Dextop's features within the Termux ecosystem when and if possible.

**Comment by nathaneltitane** [comment]
Termux:X11 preliminary implementation in progress.
