### ISSUE TITLE
system bus connection errors and bus message system

### ISSUE THREAD

**Issue by JanuszChmiel** [nathaneltitane/dextop#2]
When I have read yours readme and when I have analysed yours scripts, I would like to ask you as A experienced professional about issues, caused by The fact, that we can not run real Linux kernel in userspace variants of Linux.
For example.
Gnome-session refuses to run since system bus not available.
some /dev/fuse for example will not work.
Do you think, that is there any even complex task available, which would allow even Termux users to use dbus correctly? Try to dream and imagine, that there would be some C or C++ language expert, which would be able to extend dbus binary so it would work. Soo mate-session would not be forced to display warning message.
Error connecting to DBUs socket.
What do you think as A expert? Is there any chance?
Sure. I Am aware, that if I would like to have fully professional Linux experience, we would had to run Kqemu and Qemu, which would execute real Linux kernel and all other Linux modules. But this is not realistic anticipation. Rooting Android devices is very very complex especially for Android newer than 6.0. Using phone which have been produced with Linux kernel is also not good idea. Those phones are expensive and it is good to have A combination of Android and Linux.

Any opinion will be very nicely accepted and we could even debate together outside Github.
I have analysed many various Linux distros for Termux.
The most annoing problem is, that system bus can not exist without real Linux kernel which would had to be executed by using qemu. Qemu without Kqemu is extremely slow. In this case user would end with very slow distribution. Using desktop environment is impossible in this case.

**Comment by nathaneltitane** [comment]
Hello @JanuszChmiel 

Thanks for asking - I am no real expert per say but I have my fair share of experience with this sort of scripting and session manangement issues:

The problem with running in user space, namely using termux as the intermediary is that we are bound by the way android and termux will manage the kernel and its queries to the hardware.

Thant being said, I did my best on the softwatre side to merge both the Termux layer and the Proot/CHroot system to give a sort of transparent access to all libs and binaries throughout both 'jails' via 'proot-launch' by customizing the PATH command to include both subsystems.

When talking about C/C++ - i had encountered a similar issue and when asking the termux team - the big problem resides in the use of the underlying libraries used to complie all C interpreters and how the push their calls to the Kernelk. So unless Android actually changes or revamps the way it uses and gives access to the kernel (even while being rooted' not much of that will be possible.

By some trickery, you can tinker around with individual binaries and force them into an emulated session state by using the 'dbus-launch' command and its arguments in conjunction with various other vnc/xserver utilities to achieve a proper userspace session without too many issues. - This unfortunately rules out the more modern Gnome Desktop iterations and KDE as well (sadly).

**Comment by nathaneltitane** [comment]
@JanuszChmiel 

I will be closing this topic but please carry on in the discussions to further improve this project!

**Comment by JanuszChmiel** [comment]
Yes, I understand you.
I have been able to run mate desktop environment without big issues.
Sure, some errors with Hexadecimal number appear, mainly mate-power-manager. FOrtunately, dependent C library contain many condition blocks so it check non standard situation and mate-power manager do not crash mate desktop. It is even possible to remove mate-power-manager from ArchLinux, I did not tried it from Ubuntu, because every Linu distribution manages packages differently.

It is also possible to run
Dbus-run-session

I have been even able torun Orca screen reader and many of available text to speech synthesizers tanks to profesionally prepared Pulseaudio for Termux which uses opensless protocol.
I have been even so active, that I have downloaded gnome-session source code to find out, why systém bus connection problém auto terminate it. Unfortunately, gnome-session C source is not for amateour people. Code depend on many .h header files and finding The way would require many many time to remove The right condition. Since if I would make some non professional changes, it would have various non good results.
Unfortunately, I think, that there is not big hope, that official GNome developers would have A good will to support Termux and userspace variant of Linux distros, since it would require source code extensions from them and making many condition blocks.

Mate-session C code is able to continue, even if systém bus is not presented. There is only error message.
May be, that it would be even possible to ignore some run-time errors, modify .configure script, etc.
But it is for C compilers experts how to do that.

It is necessary to run mate with dbus-run-session.
Sure, it depend on distro.
Debian and Ubuntu based chroots are made by The way, that Dbus miracly work out of The box.
May be, that every Linux distros uses some other Dbus source code modiffication and mainly different Dbus configuration files.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
I have been heave fight to get Proot working with Huavei 10 Mate lite. Huaveis Android kernel contained something which have prevented correct case file system to work properly, so Proot developers had to spent some time to develop a work around. Now I have got Android 8 0 upgrade from July 2020 and I Am afraid, that kernel developers from Huavei have incorporated some new security routines, since ArchLinux can not be installed, there are error with sym links. So I Am now triing to install mate-desktop from Debian by using Proot-distro to find out, if Proot is suffering new issues or no.
