### ISSUE TITLE
Why I don't have the window top bar?

### ISSUE THREAD

**Issue by anonimo82** [nathaneltitane/dextop#20]
Hello everybody.
I gave Dextop another try, and I noticed I don't have the top window bar in my windows in XFCE.
Why? I guess something went wrong with my installation, is it that?

Here is a screenshot:
![Screenshot_20230503-174312_bVNC Free](https://user-images.githubusercontent.com/38261009/235967943-e78ced1e-acd2-4bbe-a11a-2374dc5d6391.jpg)

Notice I don't have the x button and so.

**Comment by nathaneltitane** [comment]
Could be an issue with the themes download: Dextop downloads and applies Arc Theme as default.
You can use the xfce settings to change it back to whatever default.

PLease let me know if that worked - I will also investigate why this did not work in your case.
