### ISSUE TITLE
cant install dextop-option

### ISSUE THREAD

**Issue by Littlemac123** [nathaneltitane/dextop#25]
I ran curl -s -L run.dxtp.app > dextop && bash dextop

And in the installer it did

[ ¤ ] Setting up dextop ///////////////////////////////////////////// [ dextop ]
                                                [ + ] Flagging /////////////////////////////////////////////// [ dextop-option ]
                                                /data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes: No such file or directory

Im on samsung s20 FE 5g andoid 13

**Comment by nathaneltitane** [comment]
> I ran curl -s -L run.dxtp.app > dextop && bash dextop
> 
> And in the installer it did
> 
> [ ¤ ] Setting up dextop ///////////////////////////////////////////// [ dextop ] [ + ] Flagging /////////////////////////////////////////////// [ dextop-option ] /data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/ubuntu/22.10/usr/share/themes: No such file or directory
> 
> Im on samsung s20 FE 5g andoid 13

Looking into it - can't seem to see what could be causing it. Running a clean install on my phone to see if it happens to rule out scripted issues.

**Comment by nathaneltitane** [comment]
Seems to be a github DNS issue with one of the dependencies: issue seems to be solved - please make sure that your internet connectivity is strong and stable.
