### ISSUE TITLE
install fails after download of ubuntu image

### ISSUE THREAD

**Issue by subjectdenied** [nathaneltitane/dextop#26]
[ + ] Creating ////////////////////////////////// [ container-image-checkpoint ]

proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/*/*, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.
[ + ] Creating /////////////////////// [ dextop-container-expansion-checkpoint ]

proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/*/*, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.
[ + ] Creating //////////////////// [ dextop-container-repositories-checkpoint ]

proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/*/*, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.
[ + ] Creating //////////////////////// [ dextop-container-packages-checkpoint ]

proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/*/*, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.
[ + ] Creating //////////////////////////// [ dextop-container-user-checkpoint ]

[ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]

[ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]

[ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]

[ + ] Creating ///////////////////////////////// [ dextop-bookmarks-checkpoint ]

[ ⬢ ] Keeping ////////////////////////////////////////////////////// [ Adwaita ]

[ ⬢ ] Keeping ////////////////////////////////////////////////////// [ hicolor ]

[ / ] Linking //////////////////////////////////////////////////////// [ icons ]

[ + ] Creating ///////////////////////////////////// [ dextop-icons-checkpoint ]

/data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/*/*/usr/share/themes: No such file or directory

-----

this happens on a fresh install

this project is amazing btw!

**Comment by nathaneltitane** [comment]
> [ + ] Creating ////////////////////////////////// [ container-image-checkpoint ]
> 
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/_/_, cwd = /root, $PATH=(null)) fatal error: see `proot --help`. [ + ] Creating /////////////////////// [ dextop-container-expansion-checkpoint ]
> 
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/_/_, cwd = /root, $PATH=(null)) fatal error: see `proot --help`. [ + ] Creating //////////////////// [ dextop-container-repositories-checkpoint ]
> 
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/_/_, cwd = /root, $PATH=(null)) fatal error: see `proot --help`. [ + ] Creating //////////////////////// [ dextop-container-packages-checkpoint ]
> 
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/cnt/_/_, cwd = /root, $PATH=(null)) fatal error: see `proot --help`. [ + ] Creating //////////////////////////// [ dextop-container-user-checkpoint ]
> 
> [ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]
> 
> [ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]
> 
> [ + ] Writing //////////////////////////////////////////////////// [ bookmarks ]
> 
> [ + ] Creating ///////////////////////////////// [ dextop-bookmarks-checkpoint ]
> 
> [ ⬢ ] Keeping ////////////////////////////////////////////////////// [ Adwaita ]
> 
> [ ⬢ ] Keeping ////////////////////////////////////////////////////// [ hicolor ]
> 
> [ / ] Linking //////////////////////////////////////////////////////// [ icons ]
> 
> [ + ] Creating ///////////////////////////////////// [ dextop-icons-checkpoint ]
> 
> /data/data/com.termux/files/home/.local/bin/frobulator: line 1282: cd: /data/data/com.termux/files/usr/cnt/_/_/usr/share/themes: No such file or directory
> 
> this happens on a fresh install
> 
> this project is amazing btw!

Thank you for your kind words!

Could be that the image address has changed due to a bump in version or removal of the ubuntu image alltogether - let me look into this.

@subjectdenied can you specify which steps you took for your install or which version of ubuntu you've tried to set up?

**Comment by subjectdenied** [comment]
@nathaneltitane it was just the default script on the website, so i guess it would be ubuntu 20.10

**Comment by nathaneltitane** [comment]
> @nathaneltitane it was just the default script on the website, so i guess it would be ubuntu 20.10

weird, no issues with urls, can you make sure you have a stable internet connection and restart the install?

**Comment by nathaneltitane** [comment]
> > @nathaneltitane it was just the default script on the website, so i guess it would be ubuntu 20.10
> 
> weird, no issues with urls, can you make sure you have a stable internet connection and restart the install?

@subjectdenied have you tried again?

**Comment by subjectdenied** [comment]
yes, i can't get it working, but i checked the extracted ubuntu image and found that it doesnt have a /usr/share/themes directory, which might be an error resulting of something going wrong before

did you try to run the whole setup process from fresh with latest script? i tried the script with a completly fresh (and updated) termux installation twice, the only thing i can think about that could be a source for the error is a systemupdate i got for my samsung phone 2 days ago, maybe it introduced some security "feature" that messes up proot somehow

also when the script fails, there are a some apt-get proccesses hanging, that autostart again after being killed

**Comment by nathaneltitane** [comment]
@subjectdenied there is in fact something that has changed! The ROOT wildcard was no longer functioning and returning the litteral ${PREFIX}/cnt/*/* rather than the expected content

Issue seemingly fixed - please try again and confirm!

**Comment by nathaneltitane** [comment]
@subjectdenied please confirm

**Comment by subjectdenied** [comment]
yes this is working now, thanks!

**Comment by nathaneltitane** [comment]
> yes this is working now, thanks!

Thank you! Use it well!
