### ISSUE TITLE
Samsung Galaxy S22 VNC port not allowed error with bVNC

### ISSUE THREAD

**Issue by ayusufsirin** [nathaneltitane/dextop#27]
I got the following error after running the command and setting the resolution:

`container-session -o vnc`

![image](https://github.com/nathaneltitane/dextop/assets/65160352/75fee84f-0cc8-4636-b9e8-8fc28491a835)

This error is shown by the popping up bVNC window.

**Comment by nathaneltitane** [comment]
@ayusufsirin hello! thank you for reporting this.
Termux:X11 is now made available during installation of termux-additions - have you tried just ```container-session -o``` which defaults to X11 method? 

I have not checked bVNC for a while as it had given me some issues a while back and was kind of overconvoluted - try setting the connection parameters in the application and see if a connection functions doing that - make sure to run ```container-session -x``` first to kill all/any connections and start fresh

**Comment by nathaneltitane** [comment]
@ayusufsirin I would like to confirm that I have just installed bVNC and used ```container-session -o vnc```and the session loaded and opened bVNC as expected.

**Comment by ayusufsirin** [comment]
May the problem originated from Android OS rights? Though, how can I give the permissions for ports? Also, my device is not rooted. But this is not the case, I think.

On the other hand, I have tried the x11 method, also. But I could not find a client to connect. Termux did not be a client, automatically.

**Comment by nathaneltitane** [comment]
> May the problem originated from Android OS rights? Though, how can I give the permissions for ports? Also, my device is not rooted. But this is not the case, I think.
> 
> On the other hand, I have tried the x11 method, also. But I could not find a client to connect. Termux did not be a client, automatically.

Rooting has no influence on whether or not the port will be accessible - I'm also unsure as to whether or not Samsung modified internal port access on S22 - may I suggest staring from scratch or using X11 instead? Both methods work on my Note 20 Ultra so far...

**Comment by ayusufsirin** [comment]
I will try it from scratch, soon. Thanks for your insane speedy responses.

**Comment by nathaneltitane** [comment]
@ayusufsirin any update?

**Comment by ayusufsirin** [comment]
Yes I just tried. But got a log about "killed":

```
[  ] >_ $ container-session -x
[ ¤ ] Setting up session /////////////////////////// [ container // 07-19-2023 ]

[ ! ] No active display server detected.

[ > ] Exiting...

[  ] >_ $ container-session -c
[ ¤ ] Setting up session /////////////////////////// [ container // 07-19-2023 ]

[  ] >_ $ container-session -o
[ ¤ ] Setting up session /////////////////////////// [ container // 07-19-2023 ]

[ > ] Starting display server...

[ > ] Generating display...

/data/data/com.termux/files/home/.local/bin/container-session: line 865: 32279 Killed                  ${load_command} > /dev/null 2>&1
[ > ] Loading desktop interface...
```

One thing I want to mention before is about my Termux. I download it from GooglePlay. Will it be a problem?

**Comment by nathaneltitane** [comment]
your output is weird, no user name and the process killing should not happen

**Comment by ayusufsirin** [comment]
Hi, again. I will try reinstalling everything by also upgrading the Termux. Do you think this may be the case?

> One thing I want to mention before is about my Termux. I download it from GooglePlay. Will it be a problem?

**Comment by nathaneltitane** [comment]
> Hi, again. I will try reinstalling everything by also upgrading the Termux. Do you think this may be the case?
> 
> > One thing I want to mention before is about my Termux. I download it from GooglePlay. Will it be a problem?

the Play Store version has been deprecated since November 2020.

Please follow my Readme and use the links provided.

**Comment by nathaneltitane** [comment]
non homogenous package signatures (various sources) - users must read and comply with ReadMe for best results.

**Comment by ayusufsirin** [comment]
Hi. You just closed the issue, but my problem is continuing. I completely remove the termux from my device then make a fresh installation. Nothing changed but termux style. I did what you wanted in ReadMe.

![Screenshot_20230802_165157_Termux.jpg](https://github.com/nathaneltitane/dextop/assets/65160352/4f72a085-9c4a-4d5e-95f9-f4eb7a21be21)

What should I do when there are no error messages as well as no displays? Please help me. I really like your project and want to use for daily.

**Comment by nathaneltitane** [comment]
> Hi. You just closed the issue, but my problem is continuing. I completely remove the termux from my device then make a fresh installation. Nothing changed but termux style. I did what you wanted in ReadMe.
> 
> ![Screenshot_20230802_165157_Termux.jpg](https://github.com/nathaneltitane/dextop/assets/65160352/4f72a085-9c4a-4d5e-95f9-f4eb7a21be21)
> 
> What should I do when there are no error messages as well as no displays? Please help me. I really like your project and want to use for daily.

What you are showing has no error messages because there are no errors to be shown at the moment...

The Dextop setup process takes you through everything you need to do to have a fully functional workstation.

1 - Did you use the Termux link provided in the readme to use the Github termux apk?
2 - Did you pay attention to, and follow all of the prompts during the setup process?

Your dextop screenshot looks normal now: you have a 'termux' prompt and all the output seems to be as expected.

Normally, if Termux:X11 was installed correctly (proper version and with permissions enabled) the ```container-session -o```  command should handle opening the application and show you the graphical session.

You can re-run ```termux-additions``` manually and try again without redoing the whole setup

**Comment by ayusufsirin** [comment]
Thanks for the reply. Yes, I install the Termux from GitHub link in ReadMe. When I try to install `termux-additions` the Package Manager gives me parsing error.
In the initial installation I did not remember like that.

**Comment by ayusufsirin** [comment]
> Thanks for the reply. Yes, I install the Termux from GitHub link in ReadMe. When I try to install `termux-additions` the Package Manager gives me parsing error.
> In the initial installation I did not remember like that.

I now installed the additions from manually downloaded .apk files. I will notify you about the results.

**Comment by ayusufsirin** [comment]
> > Thanks for the reply. Yes, I install the Termux from GitHub link in ReadMe. When I try to install `termux-additions` the Package Manager gives me parsing error.
> > In the initial installation I did not remember like that.
> 
> I now installed the additions from manually downloaded .apk files. I will notify you about the results.

Niceeee. It is OK now. I appreciate it 🙏
