### ISSUE TITLE
X not connected

### ISSUE THREAD

**Issue by kstenerud** [nathaneltitane/dextop#30]
I installed termux and termux-x11, ran the dextop installer script, and everything seems to be okay. But when I run `container-session -o x11`, it opens a window with the X logo that says "Not connected".

Is there something else I need to do to get the window manager running?

**Comment by nathaneltitane** [comment]
Hi @kstenerud , must be an issue with termux'S package management not fetching or installing required packages properly - please delete the .dextop folder in your home directory and run the setup once again without clearing your Termux setup, this should solve the issue and you will notice that the termux-packages run will be a tad slower than on the initial run.

Please advise if it has worked.

**Comment by nathaneltitane** [comment]
@kstenerud P.S.: x11 is the default - no need to specify it - ```container-session -o``` suffices

**Comment by kstenerud** [comment]
I'll check on it tonight after work. I wonder if there's some way to make the scripts fail fast in case of a broken download?

**Comment by nathaneltitane** [comment]
> I'll check on it tonight after work. I wonder if there's some way to make the scripts fail fast in case of a broken download?

Will see about that, i added a failsafe to use pkg instead of apt for now - but the 'fix' in the initial comment should work through the issue for now

**Comment by kstenerud** [comment]
I've tried deleting `.dextop` and re-running the install script multiple times in a row. Each time it tells me that a number of packages are absent on the system (notably a number of x11 packages and wayland, xfce, even sudo), and then proceeds to install them (I assume it succeeds because it doesn't complain). It always reinstalls the same packages every time.

And then once that's done, I get the same result as before.

I've also tried uninstalling and reinstalling termux. Same result every time.

This is on a Galaxy s23 running stock firmware.

**Comment by nathaneltitane** [comment]
> I've tried deleting `.dextop` and re-running the install script multiple times in a row. Each time it tells me that a number of packages are absent on the system (notably a number of x11 packages and wayland, xfce, even sudo), and then proceeds to install them (I assume it succeeds because it doesn't complain). It always reinstalls the same packages every time.
> 
> And then once that's done, I get the same result as before.
> 
> I've also tried uninstalling and reinstalling termux. Same result every time.
> 
> This is on a Galaxy s23 running stock firmware.

investigating...

**Comment by nathaneltitane** [comment]
Issue caused by termux-x11 apk being out of date - pulled the new october 26th version into the project repositories - can now launch X as expected. Please manually update the apk by downloading it from the official github repository or run termux-additions and close termux again, restart with container-session -o to check

**Comment by kstenerud** [comment]
I tried downloading and installing [`app-arm64-v8a-debug.apk`](https://github.com/termux/termux-x11/releases/tag/nightly) but no dice.

I also tried uninstalling everything (uninstalling all termux apps from my phone and then reinstalling the main termux app from https://github.com/termux/termux-app/releases/tag/v0.118.0) and reinstalling, but no dice.

I can get a desktop using https://github.com/phoenixbyrd/Termux_XFCE but not using this project :/

**Comment by nathaneltitane** [comment]
This is very weird :/ - I really spent several hours going through the scripts and on two devices - did a full clean reinstall to validate and only the apk was seemingly the culprit.

I will certainly dig deeper when I have a chance over the weekend - this is certainly not a dismissal :)

Thank you for elaborating.

**Comment by kstenerud** [comment]
I'm going to see about modifying the scripts to `set -euxo pipefail` on everything, just to get a list of what it actually ran and stop if anything fails.

Is `run.dxtp.app` serving a particular branch or tag?

**Comment by nathaneltitane** [comment]
> I'm going to see about modifying the scripts to `set -euxo pipefail` on everything, just to get a list of what it actually ran and stop if anything fails.
> 
> Is `run.dxtp.app` serving a particular branch or tag?

Sounds good - that domain serves the main dextop script under the main branch - easier than typing a really long url

**Comment by kstenerud** [comment]
I tried for a few hours, but it would take a LOT of work to update the scripts to support `-u`, so there's no easy way to debug where unbound variables are causing bugs :/

With `-e`, it breaks on `/data/data/com.termux/files/usr/bin/bash: line 1: architecture_intent: command not found`

There are thousands of errors in the various logfiles, mostly `E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock. It is held by process 24839 (apt-get)`. 

```
$ grep -r "E: " .local/var/log | wc -l
40080
```

`grep -v` filtering out the locking errors, others are:

`E: The package cache file is corrupted`
`E: Problem renaming the file /data/data/com.termux/cache/apt/srcpkgcache.bin.HWY2y6 to /data/data/com.termux/cache/apt/srcpkgcache.bin - rename (2: No such file or directory)`

It almost seems like multiple apt commands are trying to run simultaneously, with catastrophic results.

**Comment by nathaneltitane** [comment]
> I tried for a few hours, but it would take a LOT of work to update the scripts to support `-u`, so there's no easy way to debug where unbound variables are causing bugs :/
> 
> With `-e`, it breaks on `/data/data/com.termux/files/usr/bin/bash: line 1: architecture_intent: command not found`
> 
> There are thousands of errors in the various logfiles, mostly `E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock. It is held by process 24839 (apt-get)`.
> 
> ```
> $ grep -r "E: " .local/var/log | wc -l
> 40080
> ```
> 
> `grep -v` filtering out the locking errors, others are:
> 
> `E: The package cache file is corrupted` `E: Problem renaming the file /data/data/com.termux/cache/apt/srcpkgcache.bin.HWY2y6 to /data/data/com.termux/cache/apt/srcpkgcache.bin - rename (2: No such file or directory)`
> 
> It almost seems like multiple apt commands are trying to run simultaneously, with catastrophic results.

I've been investigating this for a few days and am trying to pinpoint the exact reason this is happening - it is quite distressing as the last major update (October did not show any signs of this and the installation process went through as expected on three of my devices) - I'll try and fix this asap - thank you for reporting this - I can confirm the apt lock issue and  a few other derived problems on the container side as well.

**Comment by nathaneltitane** [comment]
@kstenerud I have looked at the issues and revamped the installation process - it seems to be working.
Stale repository references and aother pkg issues unknowns seemed to have been causing problems throughout the initial phase of the installation making required packages to be installed skipped or not downloaded due tot the errors mentioned prior as well.

I will be attempting an clean install on the remainder of my devices shortly to assess the fixes.

**Comment by nathaneltitane** [comment]
Some termux packages still fail to install - 99% of specified packages are installed and functional.
termux-am fails to open applications on call (i.e.: container-session -o does not hook termux:x11 android app to bring it to front)
