### ISSUE TITLE
Dextop flags and reference files/pointers not written during setup

### ISSUE THREAD

**Issue by Richard-2481** [nathaneltitane/dextop#38]
I have a Samsung Galaxy S24 Ultra.

I downloaded and installed:
termux-app_v0.118.1+github-debug_arm64-v8a.apk
app-arm64-v8a-debug.apk
termux-api_v0.50.1+github-debug.apk

Then opened Termux and entered the following:
pkg update && pkg upgrade -y
termux-setup-storage
echo 'Home' > .storage
curl -s -L run.dxtp.app > dextop && bash dextop

After the curl function is complete including adding the Termux extra stuff, I am put into the terminal with the error:
cat: /data/data/com.termux/files/home/.dextop/dextop-login: No such file or directory

I have tried the installation several times and it always gives me this error.
When run container-session -o then container-session -u termux, then container-session -o I am just given a blank Termux:X11 window and nothing else.

**Comment by nathaneltitane** [comment]
Hello @Richard-2481 and thanks for reporting this.

The last build was tested on my devices before pushing the update but I will have a look at this sometime this evening or a little later throughout the week.

**Comment by nathaneltitane** [comment]
Confirmed.

**Comment by nathaneltitane** [comment]
Investigate at:

https://github.com/nathaneltitane/frobulator/blob/57ef4227709c2ba21987708904c6f9da9a439933/frobulator#L2210

**Comment by nathaneltitane** [comment]
@Richard-2481 testing potential fix - looked at files during setup, nothing is MIA. should be good to go soon :)

**Comment by nathaneltitane** [comment]
Temporary fix - disable frobulator.keep from icons_intent and themes_intent in setup.

Need to investigate [frobulator.keep](https://github.com/nathaneltitane/frobulator/blob/57ef4227709c2ba21987708904c6f9da9a439933/frobulator#L2358)

**Comment by nathaneltitane** [comment]
@Richard-2481 please test and confirm - thank you
