### ISSUE TITLE
Uninstallation Instructions

### ISSUE THREAD

**Issue by Seyhyun** [nathaneltitane/dextop#44]
Hello, would it be possible for the guide to be updated with instructions on how to cleanly uninstall dextop?

**Comment by nathaneltitane** [comment]
> Hello, would it be possible for the guide to be updated with instructions on how to cleanly uninstall dextop?

Sure thing! Will update soon  - in the meantime you can remove the .dextop folder in the home directory and any items loaded under $HOME/.local/bin that dextop has loaded.

**Comment by Seyhyun** [comment]
Thanks for the quick response. Is there a list of binaries that I could refer to see which ones that dextop has loaded? Also, can you confirm that the following files/directories are also generated by dextop?
- .bash_aliases
- .bash_configuration
- .bash_functions
- .bash_login
- .bash_logout
- .bash_profile
- .bashrc
- .config
- .dbus
- .gnupg
- .hushlogin
- .icons
- .local
- .termux
- .themes

**Comment by nathaneltitane** [comment]
Yes they are. ypu can refer to the main dextop script functions to see what gets loaded. Some are also automatically generated by applications being installed. Beware of deletions causing potential issues with your setup.

**Comment by nathaneltitane** [comment]
> > Hello, would it be possible for the guide to be updated with instructions on how to cleanly uninstall dextop?
> 
> Sure thing! Will update soon - in the meantime you can remove the .dextop folder in the home directory and any items loaded under $HOME/.local/bin that dextop has loaded.

Added purge option to main dextop install script - run dextop -p | --purge to permanently remove all items - kill and restart termux to continue

**Comment by ncorrea-13** [comment]
Hello, I tried to execute it but it return "Permission denied". My device is not rooted
