### ISSUE TITLE
Exclude Systemd from XFCE for container environments

### ISSUE THREAD

**Issue by kuskebabi** [nathaneltitane/dextop#45]
The reason is... it **doesn't install xfce** because it tries installing systemd too and it fails the entire apt, which... you get a broken xfce(as this script retries installing some parts again) after that.

I fixed this by
```bash
sudo apt install xfce4 systemd-
```

and for some reason `container-session -o` doesn't start xfce correctly which you have to re-run `xfce4-session"

**Comment by nathaneltitane** [comment]
can you elaborate on the process and steps of why you're saying systemd should be excluded from install?

I kind of understand the why but a concrete example and steps to reproduce will help me pinpoint what needs to be done without breaking anything else.

**Comment by nathaneltitane** [comment]
p.s.: although the systemd package is present as a dependency to some xfce components, it does not run given the nature of the containerized system because of proot.

not sure what's happening on your end.

![Screenshot_20241112_072602_Termux.jpg](https://github.com/user-attachments/assets/ea8b4f78-a06a-42c0-a511-5e9d210feabb)

**Comment by kuskebabi** [comment]
I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff

**Comment by nathaneltitane** [comment]
> I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff

I will need more context to understand what'S happening:

Device?
Rooted?
Installing dextop from scratch?
Did you install any other deployement before?
Does this happen if you install on a fresh termux?

**Comment by kuskebabi** [comment]
> > I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff
> 
> I will need more context to understand what'S happening:
> 
> Device? Rooted? Installing dextop from scratch? Did you install any other deployement before? Does this happen if you install on a fresh termux?

Samsung galaxy m34
no
yes, i also tried reinstalling like you said at readme#issues
no
i also tried resetting termux's app data so yes

**Comment by nathaneltitane** [comment]
> > > I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff
> > 
> > 
> > I will need more context to understand what'S happening:
> > Device? Rooted? Installing dextop from scratch? Did you install any other deployement before? Does this happen if you install on a fresh termux?
> 
> Samsung galaxy m34 no yes, i also tried reinstalling like you said at readme#issues no i also tried resetting termux's app data so yes

attempted to replicate - cannot get any scenario where systemd causes an issu since it actually never gets loaded...

are you installing some package or config that explicitly bypasses the way proot functions and gets this issue to start?

**Comment by kuskebabi** [comment]
> > > > I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff
> > > 
> > > 
> > > I will need more context to understand what'S happening:
> > > Device? Rooted? Installing dextop from scratch? Did you install any other deployement before? Does this happen if you install on a fresh termux?
> > 
> > 
> > Samsung galaxy m34 no yes, i also tried reinstalling like you said at readme#issues no i also tried resetting termux's app data so yes
> 
> attempted to replicate - cannot get any scenario where systemd causes an issu since it actually never gets loaded...
> 
> are you installing some package or config that explicitly bypasses the way proot functions and gets this issue to start?

its not systemd loading and causing a crash, apt tries installing it as a dependency and it fails

**Comment by nathaneltitane** [comment]
> > > > > I mean xfce fails to install in me when systemd is not excluded, it gets stuff, but fails at setting up systemd and skips all the other stuff including xfce4 stuff
> > > > 
> > > > 
> > > > I will need more context to understand what'S happening:
> > > > Device? Rooted? Installing dextop from scratch? Did you install any other deployement before? Does this happen if you install on a fresh termux?
> > > 
> > > 
> > > Samsung galaxy m34 no yes, i also tried reinstalling like you said at readme#issues no i also tried resetting termux's app data so yes
> > 
> > 
> > attempted to replicate - cannot get any scenario where systemd causes an issu since it actually never gets loaded...
> > are you installing some package or config that explicitly bypasses the way proot functions and gets this issue to start?
> 
> its not systemd loading and causing a crash, apt tries installing it as a dependency and it fails

must be an unintended bug or unmet dependency throughout the termux package ecosystem. this issue was not present on last update.
