### ISSUE TITLE
Unable to launch graphical environment in container system

### ISSUE THREAD

**Issue by shreyas-shriyan** [nathaneltitane/dextop#46]
Steps:
1. install according to docs
2. run container-session -u termux
3. run container-session -o
![Screenshot_20241123_034757_Termux](https://github.com/user-attachments/assets/d734a415-6d8d-4704-a8d9-4b7187c6caa4)

termux x11 is blank
xfce works fine in termux system

**Comment by nathaneltitane** [comment]
Working on a new session selector - in the meantime do 'container-session -x' then reload using 'container-session -u termux'

**Comment by nathaneltitane** [comment]
> Steps:
> 
> 1. install according to docs
> 2. run container-session -u termux
> 3. run container-session -o
>    ![Screenshot_20241123_034757_Termux](https://private-user-images.githubusercontent.com/51715896/389123819-d734a415-6d8d-4704-a8d9-4b7187c6caa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTY2MDUsIm5iZiI6MTczMjQ5NjMwNSwicGF0aCI6Ii81MTcxNTg5Ni8zODkxMjM4MTktZDczNGE0MTUtNmQ4ZC00NzA0LWE4ZDktNGI3MTg3YzZjYWE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NmI4OTU4YzRjYWZiYzVlZjFkY2RkMjkyZWU3YTIxOTJkN2MzOTY4ZDg3ZGJjMjU2OWQ0ZjA4YzhjMzcwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j9-qpOWA-drTYsaTV4n3mH1FQkMzIh7Y6Vql6ctekFY)
> 
> termux x11 is blank xfce works fine in termux system

Reference #43  - closing this since it is a duplication of mentionned ticket

**Comment by nathaneltitane** [comment]
> Steps:
> 
> 1. install according to docs
> 2. run container-session -u termux
> 3. run container-session -o
>    ![Screenshot_20241123_034757_Termux](https://private-user-images.githubusercontent.com/51715896/389123819-d734a415-6d8d-4704-a8d9-4b7187c6caa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzYyNjgsIm5iZiI6MTczMzA3NTk2OCwicGF0aCI6Ii81MTcxNTg5Ni8zODkxMjM4MTktZDczNGE0MTUtNmQ4ZC00NzA0LWE4ZDktNGI3MTg3YzZjYWE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE3NTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTZjZjY2MzlhMjVjYzY4NjhhN2Y5MmM4YTAxMDJkNWZjZjMxYmI3NjZmZGRiOWJmNmYwMzI2M2Q0ZGU3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JDFJovpXa1MgDpm2jHG20cLOzNGPOtqeuO572FGxtCQ)
> 
> termux x11 is blank xfce works fine in termux system

issue has been identified and corrected - this stems from a change in proot/bash under termux - Dextop used to be able to automatically launch the graphical session and Termux:X11 using 'am' - for some reason this does not occur anymore.

please see latest release and update utilities as per the Readme to fix this :)

**Comment by nathaneltitane** [comment]
@twaik any insight?

**Comment by nathaneltitane** [comment]
Fixed.
